kind: pipeline
type: docker
name: default

steps:
- name: waiter
  image: golang
  commands:
  - date
  - ./loop.sh
  - date

- name: chef
  image: golang
  commands:
  - date
  - sleep 17
  - echo 'foo bar' > sleep.txt
  - date

- name: desert
  image: golang
  commands:
  - cat sleep.txt
  depends_on:
  - chef
  - waiter
