kind: pipeline
type: docker
name: default

steps:
- name: chef
  detach: true
  image: python:2.7
  commands:
  - python -m SimpleHTTPServer 8080

- name: waiter
  image: python:2.7
  commands:
  - sleep 5
  - curl chef:8080/CHANGELOG.md
