version: 2.1

jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.7.1
    steps:
      - checkout
      - run: lein deps
      - run: lein test
      - run:
          command: lein cloverage --codecov
          when: always
      - store_artifacts:
          path: target/coverage
          when: always
      - persist_to_workspace:
          root: .
          paths: [.]

  plugin_test:
    docker:
      - image: plugins/codecov
    steps:
      - attach_workspace:
          at: .
      - run:
          command: drone-codecov
          #environmenmt:
          environment:
            PLUGIN_TOKEN: 5a20f422-b19d-4a49-918b-0ba56eab85e3
            PLUGIN_FILES: target/coverage/codecov.json
            PLUGIN_FLAGS: server
            DRONE_REPO: << pipeline.project.git_url >>
            DRONE_BRANCH: << pipeline.git.branch >>
            DRONE_COMMIT: << pipeline.git.revision >>
            DRONE_TAG: << pipeline.git.tag >>
            DRONE_BUILD_NUMBER: << pipeline.number >>
            #DRONE_BUILD_LINK: from env var
            #DRONE_PULL_REQUEST: from env var

workflows:
  wf:
    jobs:
      - build
      - plugin_test:
          requires: [build]
