version: 2.1

orbs:
  codecov: codecov/codecov@1.0.4

jobs:
  build:
    docker:
      - image: circleci/clojure:lein-2.7.1

    #environment:
    #  CODECOV_TOKEN: 5a20f422-b19d-4a49-918b-0ba56eab85e3

    steps:
      - checkout
      - run: lein deps
      - run: lein test

      # You can set it in your CI environment variables. CODECOV_TOKEN="5a20f422-b19d-4a49-918b-0ba56eab85e3"
      # - run: lein cloverage --codecov

      # - codecov/upload:
      #     file: target/coverage/codecov.json
      #     flags: server

      # - store_artifacts: {path: target/coverage}
